### ISSUE TITLE
Handle `-` as version separator in addition to `+`

### ISSUE THREAD

**Issue by lunaryorn** [scalacenter/sbt-version-policy#103]
sbt-dynver recommends to use `-` in case `+` doesn't work (e.g. docker).  See https://github.com/dwijnand/sbt-dynver#portable-version-strings>.

However this plugin doesn't seem to detect the previous version correctly:  If I set `ThisBuild / dynverSeparator := "-"` then `versionPolicyPreviousVersions` is empty unless a previous version exists in the local Ivy repository. This makes version checks spuriously succeed on my CI (where the local repo is empty), even if I make a binary incompatible change, because mimaPreviousArtifacts remains empty.

Probably related, `versionPolicyPreviousVersions` finds published snapshot versions, e.g. `2.0.0-2-d7f5b21a`, for its version check.

**Comment by julienrf** [comment]
Thank you for reporting.
I think this logic is handled by coursier. Maybe @alexarchambault can shed some light?

**Comment by lunaryorn** [comment]
To work around this issue I now leave `dynverSeparator` alone and instead change version for native packager only with `Docker / version := version.value.replace('+', '-')`.  As far as I can see it works, and it's good enough for me.

I'd appreciate a short line about this in `README`, but otherwise we can also close this issue again :slightly_smiling_face:
