### ISSUE TITLE
[Question] Does adding BinaryAndSourceCompatible for the first time make the next release binary incompatible?

### ISSUE THREAD

**Issue by naderghanbari** [scalacenter/sbt-version-policy#113]
Hi, first of all thanks for this plugin.

If this plugin is added for the first time to a library, and the intention is 

```
ThisBuild / versionPolicyIntention := Compatibility.BinaryAndSourceCompatible
```

Does that make the next release binary incompatible with the current release?

I suppose the answer is no, but this happened [here](https://github.com/scala/scala-java8-compat/pull/211/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R22) in `scala-java8-compat` library version `1.0.0-RC1` and it wasn't changed until `1.0.1`. But in one of my projects I see a conflict between version `0.9.1` and `1.0.0`.

```
[error] (dependencyTreeIgnoreMissingUpdate) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]         * org.scala-lang.modules:scala-java8-compat_2.13:1.0.0 (early-semver) is selected over 0.9.1
[error]             +- com.typesafe.akka:akka-actor_2.13:2.6.17           (depends on 1.0.0)
[error]             +- io.getquill:quill-jasync_2.13:3.7.1                (depends on 0.9.1)
```

Cheers and thanks in advance.

**Comment by julienrf** [comment]
Hi @naderghanbari,

What you see in your project is an error reported by the fact that akka depends on scala-java8-compat 1.0.0 and quill depends on scala-java8-compat 0.9.1, and those versions of scala-java8-compat are not binary compatible.

You need to either downgrade akka to a version that uses scala-java8-compat 0.9, or upgrade quill to a version that uses scala-java8-compat 1. By the way, I think the akka team should have bumped their major version number when they bumped their dependency to scala-java8-compat from 0.9 to 1, but that’s another story.

That being said, I didn’t answer your question. When you add `versionPolicyIntention := Compatibility.BinaryAndSourceCompatible` you ensure that your next release will be both binary and source compatible with your last release.

**Comment by naderghanbari** [comment]
Thanks for your answer @julienrf .

> those versions of scala-java8-compat are not binary compatible

> When you add versionPolicyIntention := Compatibility.BinaryAndSourceCompatible you ensure that your next release will be both binary and source compatible with your last release

- Timeline
  - version `0.9.x` (doesn't have any versionPolicyIntention, does not depend on `sbt-version-policy`)
  - version `1.0.0` (introduces `versionPolicyIntention := Compatibility.BinaryAndSourceCompatible`)
  - version `1.0.1` (changes versionPolicyIntention accidentally)
  - version `1.0.2` (fixes the accidental change)
  
My understanding is
  - `1.0.0` is binary compatible with `0.9.x`
  - `1.0.1` is binary incompatible with `1.0.0` and `0.9.x`
  - `1.0.2` is binary compatible with `1.0.1` and incompatible with `1.0.0` and `0.9.x`
  
Where is the flaw in my understanding?

**Comment by julienrf** [comment]
Hi,
That’s a good point that when `1.0.0` was released its `versionPolicyIntention` was `BinaryAndSourceCompatible` (although it is usually `Compatibility.None` when we cut a major release). However, MiMa was [configured](https://github.com/scala/scala-java8-compat/blob/v1.0.0/build.sbt#L79) to compare 1.0.0 with 1.0.0-RC1. This means that 1.0.0 was checked to be compatible with 1.0.0-RC1, not 0.9.x.

That being said, maybe 1.0.0 is _effectively_ binary compatible with 0.9.x, I don’t know this project well enough. But the fact that they bumped the major version number and they declare the versioning scheme `early-semver` means that tools (such as sbt) assume that 0.9.x and 1.0.0 are incompatible.

**Comment by julienrf** [comment]
Maybe @SethTisue can shed some light about the actual state of compatibility between 0.9.x and 1.0.0, and the motivation for bumping the major version number?

In case 1.0.0 is indeed compatible with 0.9.x, you can tell it to sbt with:

~~~ scala
libraryDependencySchemes += "org.scala-lang.modules" % "scala-java8-compat" %% "always"
~~~

But  make sure to remove this line when your project does not depend on 0.9.x anymore.

**Comment by SethTisue** [comment]
The primary motivation for going to 1.0 for scala-java8-compat was to signal future binary compatibility, not to signal any incompatibility between 0.9.x and 1.x.

**Comment by naderghanbari** [comment]
Thanks @julienrf and @SethTisue. `always` workaround works fine in my case, until we move off of `0.9.x`.
