### ISSUE TITLE
feedback wanted: establish a way to let clients explain how to parse version numbers

### ISSUE THREAD

**Issue by jgogstad** [scalacenter/sbt-version-policy#139]
opening this as an issue for discussion, discussions are not enabled for this repo.

sbt-version-policy currently relies on coursier `versions` for parsing version numbers and correctly identify tags. If coursier doesn't support the version naming scheme that a dependency uses, we get false positives from `versionPolicyReportDependencyIssues`. The only possible solution is to ignore the dependency; Coursier can't know about every version naming scheme out there, and sbt-version-policy has no hooks that lets clients inject logic that explains a concrete version name scheme.

I think such a hook would be useful. Maybe something along the lines of

```scala
val versionMap = settingKey[PartialFunction[ModuleId, String]]("Custom parsing logic for extracting version number for a given module")
```

I'm happy to take a stab at contributing this, but I'd like feedback from the library maintainers first, hence this issue.

To give one concrete example of common dependency out there with a custom versioning scheme, take Google's generated API clients, see for instance [googleapis/google-api-java-client-services/google-api-services-iam/](https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-iam/v1/). Versions looks like `v1-rev20211104-1.32.1` the client version is `1.32.1` and the API version it targets is `v1-rev20211104`. To my knowledge Google uses some version of semantic versioning where major version increase means break in binary compatibility.

Orthogonal to this is the custom [dynver separator issue](https://github.com/scalacenter/sbt-version-policy#unsupported-custom-dynverseparator). They feel kind of related—explaining version numbers. So maybe it's possible to shoot two birds with one stone here?

**Comment by julienrf** [comment]
Thank you for opening this discussion! I think it makes sense. The name of the key should have the prefix `versionPolicy`. For example, `versionPolicyModuleVersionCustomExtractor`?

**Comment by laughedelic** [comment]
How about `versionPolicyModuleVersionExtractor` which just takes the version literally as the (current) default:

```scala
versionPolicyModuleVersionExtractor := { moduleId => moduleId.revision }
```

Or `versionPolicyModuleRevisionExtractor` to align with the naming in [`ModuleID`](https://www.scala-sbt.org/release/api/sbt/librarymanagement/ModuleID.html#revision:String).

**Comment by laughedelic** [comment]
Maybe it should return a `coursier.version.Version` since that's what the plugin works with?
