### ISSUE TITLE
versionCheck Doesn't Honor versionScheme For PVP

### ISSUE THREAD

**Issue by isomarcte** [scalacenter/sbt-version-policy#60]
When `versionScheme` is set to "pvp" the `versionCheck` task doesn't calculate the correct result.

See: https://github.com/scalacenter/sbt-version-policy/blob/v1.0.0-RC4/sbt-version-policy/src/main/scala/sbtversionpolicy/Compatibility.scala#L67

This check assumes that the first component is the major version, the second the minor, and the third the patch, however if the library is PVP, e.g. if `versionScheme := "pvp"`, then the first two components represent the major version.

**Comment by isomarcte** [comment]
Maybe I'm a little confused about the intention here. 

I note from the README,

```
 sbt-version-policy:

    configures sbt-mima to guarantee that your library follows the recommended versioning scheme,
    ensures that none of your dependencies are bumped or removed in an incompatible way.
```

Which has a link to https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html#recommended-versioning-scheme. 

This would imply that this plugin assumes that the library it is being run on is always SemVer. However later on in the README,

> pvp: assumes the matched modules follow package versioning policy (quite common in Scala),

Which makes it sound like it supports PVP...

Is this plugin intended to support SemVer/PVP/Strict/Always e.g. from coursier, or just SemVer while providing support for _dependencies_ which are SemVer/PVP/Strict/Always?

**Comment by julienrf** [comment]
Hey @isomarcte, the plugin assumes that you will use Early SemVer for your library. However, if you depend on other libraries that use pvp, you can declare that by using `versionPolicyDependencySchemes`.

Also, does #58 clarify your doubts?

**Comment by julienrf** [comment]
I’m closing this issue as I think the current behavior is expected, but feel free to re-open the discussion.

**Comment by isomarcte** [comment]
@julienrf would you be open to a PR which allows declaring the version type, derived from `versionScheme` if possible, and configuring MiMa based on that?

**Comment by julienrf** [comment]
May I ask what is the motivation for not using Early SemVer?

**Comment by isomarcte** [comment]
@julienrf are you asking why a library would use anything other than early semver?

**Comment by julienrf** [comment]
Yes :slightly_smiling_face:

**Comment by isomarcte** [comment]
@julienrf I mean, there are lots of reasons, mostly subjective. I would normally assume that most projects which are using Early SemVer will eventually graduate to just normal semver, what coursier calls SemVerSpec.

The reasons for not exclusively using Early SemVer being that you can not differentiate at the version level between new symbols and just internal bug fixes, e.g. 2.0.0 -> 2.0.1 in SemVer means you didn't change the public API at all, 0.1.0 -> 0.1.1 means the public API _may_ have changed, but only with new symbols, but it also could just be a bug fix.

As to why to use PVP over SemVer, one would do so when one wants to be able to use two different numbers to denote different binary breaking changes. Often in Haskell you use the first major version number to denote an transitive dependency set, and the second one to denote internal binary breaking changes, e.g.

0.0.0.1 -> 0.1.0.0 (may mean you removed as symbol/signature)
0.0.0.1 -> 1.0.0.0 (may mean you updated a dependency which is known to break binary compatibility, e.g. your code depends on MTL and MTL was updated from 1.0.0.0 -> 2.0.0.0 (or 1.1.0.0))

Though that usage is not defined in PVP and left up to the library author's discretion.

**Comment by julienrf** [comment]
Thank you @isomarcte for writing this up!

I am not really convinced that these use cases make sense in a JVM-based world. For instance, I don’t think it is worth distinguishing between updating a dependency which is known to break binary compatibility, and releasing a binary breaking change. In both cases, this is the same type of incompatibility, which we signal in Early SemVer by bumping the major version number.

To be honest, I was thinking of removing the pieces of code in sbt-version-policy that assume that `versionScheme` _can_ be different from `"early-semver"`. I think this would simplify the plugin implementation. However, if several people think we should support other versioning schemes, I see two solutions: either we support them all in sbt-version-policy, or we create sbt-pvp-policy, and so on for the other versioning schemes.

As you noticed, `versionCheck` does not work if `versionScheme` is not `"early-semver"`. I think `versionPolicyCheck` does work with [other versioning schemes](https://github.com/scalacenter/sbt-version-policy/tree/master/sbt-version-policy/src/sbt-test/sbt-version-policy/mima-pvp), though, so you would only have to fix `versionCheck` if we want to support other versioning schemes in sbt-version-policy.
