### ISSUE TITLE
Scala 3 compatible

### ISSUE THREAD

**Issue by gaeljw** [scalacenter/sbt-version-policy#62]
Hello,

I was just trying out the plugin on different projects and it seems to encounter an issue with Scala 3 projects.

When looking for the previous version to run the checks (`sbt versionPolicyCheck` running), it fails to retrieve it:
```
[error] sbt.librarymanagement.ResolveException: Error downloading io.github.gaeljw:typetrees_3.0.0-RC1_3.0:0.2.0
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/io/github/gaeljw/typetrees_3.0.0-RC1_3.0/0.2.0/typetrees_3.0.0-RC1_3.0-0.2.0.pom
```

It's looking for a weird artifact name `io.github.gaeljw:typetrees_3.0.0-RC1_3.0:0.2.0` instead of `io.github.gaeljw:typetrees_3.0.0-RC1:0.2.0`.

I guess it may be more related to the "RC1" than Scala 3.

**Comment by SethTisue** [comment]
I'm hitting this as well at https://github.com/scala/scala-parallel-collections/pull/164

**Comment by SethTisue** [comment]
perhaps this is a problem with sbt-mima rather than in this repo per se? https://github.com/lightbend/mima/issues/613
