### ISSUE TITLE
`versionPolicyCheck` should respect `skip / publish` setting

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/sbt-version-policy#63]
if `skip / publish` is `true`, then there's no check to do

this came up at https://github.com/scala/scala-parallel-collections/pull/164

**Comment by julienrf** [comment]
I also see the setting `publishArtifact`. Does someone know how to reliably detect that a module is not published? (`skip / publish` is not always used)

**Comment by julienrf** [comment]
See #64

**Comment by SethTisue** [comment]
hmm, I'm not sure if it should also check `publishArtifact`, or what
